[package]
name = "dc"
authors = ["Ben Sully <ben.sully@grafana.com"]
version = "0.1.0"
edition = "2018"

[dependencies]
color-eyre = "0.5"
tracing = "0.1.26"
tracing-error = "0.1.2"
tracing-subscriber = "0.2.20"
